on:
  workflow_call:
    secrets:
      WRITE_TOKEN_CLASSIC:
        required: true

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build client library
      id: build-lib
      env:
        GITHUB_TOKEN: ${{ secrets.WRITE_TOKEN_CLASSIC }}
      run: |
        cat << EOF > .npmrc
        @bespoken-ai:registry=https://npm.pkg.github.com
        //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
        EOF
        npm ci
        
    - name: Publish 
      id: publish-lib
      run: |
        git config --global user.email "bot@4bitcafe.com"
        git config --global user.name "Automated Release"
        npm version patch
        npm run postversion
        npm publish