on:
  workflow_call:
    secrets:
      WRITE_TOKEN_CLASSIC:
        required: true

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com'
      
    - name: Publish 
      id: publish-lib
      run: |
        git config --global user.email "bot@4bitcafe.com"
        git config --global user.name "Automated Release"
        npm version patch
        npm run postversion

    - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WRITE_TOKEN_CLASSIC }}