on:
  workflow_call:
    secrets:
      WRITE_TOKEN_CLASSIC:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com'
      
    - name: Prepare 
      id: publish-lib
      run: |
        npm ci
        git config --global user.email "bot@4bitcafe.com"
        git config --global user.name "Automated Release"
        npm version patch
        npm run postversion

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.WRITE_TOKEN_CLASSIC }}