name: 'Release version'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yaml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      WRITE_TOKEN_CLASSIC: ${{ secrets.WRITE_TOKEN_CLASSIC }}